// Code generated by the multiversx-sc multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           46
// Async Callback (empty):               1
// Total number of exported functions:  48

#![no_std]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    typevalue
    (
        insert_address
        storageAddress
        insert_token_identifier
        storageTokenIdentifier
        insert_egld_or_esdt_token_identifier
        storageEgldOrEsdtTokenIdentifier
        insert_managed_vec_managed_buffer
        storageManagedVecManagedBuffer
        insert_managed_vec_i64
        storageManagedVecI64
        insert_i8
        insert_i16
        insert_i32
        insert_i64
        insert_big_int
        storageI8
        storageI16
        storageI32
        storageI64
        storageBigInt
        insert_u8
        insert_u16
        insert_u32
        insert_u64
        insert_big_uint
        storageU8
        storageU16
        storageU32
        storageU64
        storageBigUint
        insert_my_struct
        storageMyStruct
        insert_my_struct2
        storageMyStruct2
        insert_managed_vec_my_struct2
        storageManagedVecMyStruct2
        insert_set_mapper_address
        insert_map_mapper_token_identifier_address
        StorageSetMapperAddress
        StorageMapMapperTokenIdentifierAddress
        insert_tuple_i64_bool
        storageTupleI64Bool
        insert_tuple_i64_bool_managed_buffer
        storageTupleI64BoolManagedBuffer
        insert_tuple_managed_vec_i64_bool
        storageTupleManagedVecI64Bool
    )
}

multiversx_sc_wasm_adapter::empty_callback! {}
